name: hf-onnx-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - requests>=2.28.2
      - numpy>=1.24.0
      - onnx>=1.14.0
      - onnxruntime>=1.15.0
      - azure-ai-ml>=1.3.0
      - azure-identity>=1.13.0
      - transformers>=4.30.0
      - torch>=2.0.0
      - mlflow>=2.5.0
      - azureml-mlflow>=1.50.0
